apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-deployment
  namespace: global
  labels:
    app: global
spec:
  replicas: 3
  selector:
    matchLabels:
      app: global
  template:
    metadata:
      labels:
        app: global
    spec:
      containers:
      - name: frontend
        image: aryad/multiclusteringress:sample-app.v1
        ports:
        - containerPort: 8080
