apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: global-ingress
  namespace: global
spec:
  template:
    spec:
      backend:
        serviceName: global-mcs
        servicePort: 8080
